name       : wiznote
version    : 2.5.1
release    : 2
source     :
    - https://github.com/WizTeam/WizQTClient/archive/v2.5.1.tar.gz : a29f10d77009b527cdb132ee3466279c2707415811b85ffd8611b1327966588f
license    : GPL-3.0-or-later
component  : office.notes
summary    : cross-platform cloud based note-taking client
description: |
    WizNote is an open-source cross-platform cloud based note-taking application
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5WebSockets)
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
