name       : wiznote
version    : 2.5.1
release    : 1
source     :
    - https://github.com/WizTeam/WizQTClient/archive/v2.5.1.tar.gz : 8bddfc6b2362fda5e856492cd9441105ee7e7cea4b6eafdf9a71b61bdfae3cc1
license    : GPL-3.0
component  : office.notes
summary    : cross-platform cloud based note-taking client
description: |
    WizNote is an open-source cross-platform cloud based note-taking application
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5WebSockets)
    - libboost-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
