name       : wiznote
version    : 2.8.5
release    : 5
source     :
    - https://github.com/WizTeam/WizQTClient/archive/v2.8.5.tar.gz : 4047a9dd762947755bcebc5cc40828ff6cf62549e624934d317c17318b996d08
homepage   : https://www.wiz.cn/
license    : GPL-3.0-or-later
component  : office.notes
summary    : cross-platform cloud based note-taking client
description: |
    WizNote is an open-source cross-platform cloud based note-taking application
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(x11)
    - libboost-devel
setup      : |
    sed -i '/#include <QPainter>/a #include <QPainterPath>' $workdir/src/sync/WizAvatarHost.cpp
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
